### ISSUE TITLE
hello, i want to know how can i get "ACASXU_run2a_1_1_tiny_2.nnet"?

### ISSUE THREAD

**Issue by l-outsider** [DanielMagen/cegar_python#1]
hello, i want to know how can i get the file named "ACASXU_run2a_1_1_tiny_2.nnet" that you write in “example_of_running_cegar/t_network.py”?

---

i am very interesting in your cegar_python framework, and my teacher asked me to try to use this framework, but i seem dont know how to use it. Can you talk briefly？

**Comment by DanielMagen** [comment]
I took them from https://github.com/guykatzz/Marabou/tree/master/resources/nnet/acasxu
but I see that Guy changed the files there, so you may have to contact him to get those files.

regarding the usage,
there is an example here
https://github.com/DanielMagen/cegar_python/blob/master/example_of_running_cegar/t_network.py

but note that this implementation is not complete.
it's about 99% complete, but it only supports 4 actual networks.
as you can see in Network.py, one of the arguments that init gets is called "which_acas_output" which tells the class which of the 4 networks it is being given. 
the amount of work required to complete the implementation is not that big if I remember correctly, you just need to find a way to replace the "hard_code_acas_output_properties" function in the Network class with a general function that would know how to deal with any network. unfortunately, it sort of requires you to already know what you're doing, i.e. you need to understand cegar (not that hard), read and understand the code I wrote to the level you could change what you want (hard because it's long), and come up with a way to implement the missing function. 

I think that talking to Guy or Yizhak would be your best way forward.
this is his website where you would find the necessary contact information:
https://www.katz-lab.com/

good luck!

**Comment by l-outsider** [comment]
first，thank you very much!


and i want to confirm, is your repository the implementation of the framework mentioned in the paper 《An Abstraction-Based Framework for Neural》?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Daniel Magen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月20日(星期六) 下午3:07
收件人:&nbsp;"DanielMagen/cegar_python"<cegar_python@noreply.github.com&gt;;
抄送:&nbsp;"李文驰"<787552171@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DanielMagen/cegar_python] hello, i want to know how can i get "ACASXU_run2a_1_1_tiny_2.nnet"? (#1)





 
Closed #1.
